# Generated by Django 2.1.5 on 2019-01-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='test',
            new_name='text',
        ),
    ]
